"""add admin_audit_logs table

Revision ID: 60e46adfb2a0
Revises: 665de6dacc64
Create Date: 2026-07-25 16:12:34.282106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e46adfb2a0'
down_revision: Union[str, Sequence[str], None] = '665de6dacc64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_audit_logs', sa.Column('target_type', sa.String(length=100), nullable=False))
    op.add_column('admin_audit_logs', sa.Column('target_id', sa.Integer(), nullable=False))
    op.alter_column('admin_audit_logs', 'admin_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('admin_audit_logs', 'entity_type')
    op.drop_column('admin_audit_logs', 'entity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_audit_logs', sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('admin_audit_logs', sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('admin_audit_logs', 'admin_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('admin_audit_logs', 'target_id')
    op.drop_column('admin_audit_logs', 'target_type')
    # ### end Alembic commands ###
